sudo: required

services:
  - docker

before_install:
  - docker build -t durgeshpatel317/docker-react -f Dockerfile.dev .

script:
  - docker run durgeshpatel317/docker-react npm run test -- --covergage